[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.8"
ZOLA_VERSION = "0.15.2"

# Site title in navbar
SITE_TITLE = "Tea's Heartbreaker Roleplaying Game"
# Site URL
SITE_URL = "https://teateatea.netlify.app"

# Site Timezone, I think this is for the light/dark setting?
TIMEZONE = "Asia/Hong_Kong"
# Site repo URL
REPO_URL = "https://github.com/teateatea/kettle"

# Site title on landing page
LANDING_TITLE = "Welcome!"
# Site description on landing page
LANDING_DESCRIPTION = "This is my custom roleplaying game <i>(which are often called heartbreaker games)</i>. The rules are based on Old School Essentials, the Goblin Laws of Gaming, and any other ideas that match my intended game experience.<br><br>Thank you for playing!"

# Text in landing page button
LANDING_BUTTON = "Explore"
# The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "home"



# # Text in landing page button
# LANDING_BUTTON = "Explore"
# # Site description on landing page
# LANDING_DESCRIPTION = "I have nothing but intelligence."
# # The Markdown page linked to landing page button (e.g. put home for ./home.md)
# LANDING_PAGE = "home"
# # Site title on landing page
# LANDING_TITLE = "My Second Brain"
# PYTHON_VERSION = "3.8"
# # Site repo URL
# REPO_URL = "https://github.com/ppeetteerrs/obsidian-zola"
# # Site title in navbar
# SITE_TITLE = "Example Site"
# # Site URL
# SITE_URL = ""
# # Site Timezone
# TIMEZONE = "America/Toronto"
# ZOLA_VERSION = "0.15.2"
# # How to sort notes on the right sidebar ("date" or "title"), defaults to "title" if missing or invalid
# SORT_BY = "title"